[package]
name = "shucker"
version = "0.1.0"
edition = "2021"
license = "GPLv3"

[build-dependencies]
anyhow = "1"
quote = "1"
syn = "2"
prettyplease = "0.2"
proc-macro2 = "1"

[dependencies]
anyhow = "1"
url = "2"
regex = "1"
itertools = "0.13"

[dev-dependencies]
pretty_assertions = "1"