on: 
    push:
      branches:
        - main
    pull_request:
  
name: Continuous integration
jobs:
    test:
      name: Test suite
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.0
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
            components: clippy, rustfmt
        - uses: Swatinem/rust-cache@v2.2.1
        - name: Check formatting
          run: cargo fmt -- --check
        - name: Clippy
          run: cargo clippy
          env:
            RUSTFLAGS: -Dwarnings
        - name: Install cargo-binstall
          run: |
            curl --location --remote-name https://github.com/ryankurte/cargo-binstall/releases/download/v0.11.1/cargo-binstall-x86_64-unknown-linux-musl.tgz
            tar -zxvf cargo-binstall-x86_64-unknown-linux-musl.tgz
            mv cargo-binstall ~/.cargo/bin
            ls -l ~/.cargo/bin
        - name: Install "build all features"
          run: cargo binstall cargo-all-features --no-confirm --version 1.7.0
        - name: Build all features
          run: cargo build-all-features
        - name: Test all features
          run: cargo test-all-features          
          env:
            RUST_LOG: debug
        - name: Install asdf & tools
          uses: asdf-vm/actions/install@v3            
        - name: Python build/test
          run: |
            make build
            make type-check
            make unittests
            make pre-commit
    
    minimal-versions:
      name: minimal versions check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.0
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: nightly
        - name: Remove lock
          run: rm Cargo.lock
        - run: cargo build -Z minimal-versions
      
    dependency-updates:
      name: dependency updates
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.0
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - name: Update packages
          run: cargo update
        - name: Build and test
          run: cargo test --all-features -- --nocapture
          env:
            RUST_LOG: debug